language: node_js
node_js:
- '8'
install: true
branches:
  only:
  - master
  - feat/build-dist

env:
  global:
  - GIT_COMMITTER_NAME="WWA Helper"
  - GIT_COMMITTER_EMAIL="matsuyuki.eca@gmail.com"
  - GIT_AUTHOR_NAME="WWA Helper"
  - GIT_AUTHOR_EMAIL="matsuyuki.eca@gmail.com"
script:
- openssl aes-256-cbc -K $encrypted_b56949f416a5_key -iv $encrypted_b56949f416a5_iv -in wwa_helper.enc -out ~/.ssh/id_rsa -d
- chmod 0600 ~/.ssh/id_rsa
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- npm config set -g production false
- npm install && npm run bootstrap && npm run build && npm run make-dist
- git clone git@github.com:WWAWing/Releases.git
- cp ./packages/build-utils/output/*.zip Releases
- WWA_VERSION=$(./getEngineVersion.sh)
- pushd Releases
- mv wwawing-dist.zip wwawing-dist-latest.zip
- mv wwawing-update.zip wwawing-update-latest.zip
- cp wwawing-dist-latest.zip wwawing-dist-$(echo $WWA_VERSION).zip
- cp wwawing-update-latest.zip wwawing-update-$(echo $WWA_VERSION).zip
- git add -A
- git commit -m "RELEASED $WWA_VERSION"
- git push origin master
