[build]
  base = "/"
  publish = "packages/engine/lib"
  command = "npm i && npm run build && npm run deploy"

[build.environment]
  NODE_VERSION = "22.20.0"
  NPM_VERSION = "11"
  # node-gyp が v3.6.0 以上の Python を要求している
  PYTHON_VERSION = "3.8"
