[build]
  base = "/"
  publish = "packages/engine/lib"
  # npm i の段階で prepareスクリプトが走って production ビルドされるので、できているものをデプロイする
  command = "npm run bootstrap:netlify && npm run deploy"

[build.environment]
  # node-gyp が v3.6.0 以上の Python を要求している
  PYTHON_VERSION = "3.10.1"