var loader_conf;(function(b){b.conf={is_worker:!0}})(loader_conf||(loader_conf={}));var loader_util;(function(b){b.new2DArray=function(b,a){var h,e=Array(b);for(h=0;h<e.length;h++)e[h]=Array(a);return e};b.signedByte=function(b){b%=256;return 128<=b?b-256:b}})(loader_util||(loader_util={}));var loader_wwa_data;
(function(b){var d=function(){function a(){}a.ITEMBOX_SIZE=12;a.MAP_ATR_MAX=60;a.OBJ_ATR_MAX=60;a.OLD_MAP_ATR_MAX=40;a.OLD_OBJ_ATR_MAX=40;a.ATR_CROP1=1;a.ATR_CROP2=2;a.ATR_TYPE=3;a.OBJECT_RANDOM=16;a.SYSTEM_MESSAGE_NUM=20;a.IMGPOS_DEFAULT_YESNO_X=3;a.IMGPOS_DEFAULT_YESNO_Y=1;a.IMGRELPOS_YESNO_YES_X=0;a.IMGRELPOS_YESNO_NO_X=1;a.IMGRELPOS_YESNO_YESP_X=2;a.IMGRELPOS_YESNO_NOP_X=3;a.IMGPOS_DEFAULT_PLAYER_X=2;a.IMGPOS_DEFAULT_PLAYER_Y=0;a.IMGPOS_DEFAULT_CLICKABLE_ITEM_SIGN_X=0;a.IMGPOS_DEFAULT_CLICKABLE_ITEM_SIGN_Y=
0;a.DEFAULT_DISABLE_SAVE=!1;a.DEFAULT_OLDMAP=!1;a.DEFAULT_OBJECT_NO_COLLAPSE=!1;a.DEFAULT_FRAME_COLOR_R=255;a.DEFAULT_FRAME_COLOR_G=255;a.DEFAULT_FRAME_COLOR_B=255;a.DEFAULT_FRAMEOUT_COLOR_R=96;a.DEFAULT_FRAMEOUT_COLOR_G=96;a.DEFAULT_FRAMEOUT_COLOR_B=96;a.DEFAULT_STR_COLOR_R=0;a.DEFAULT_STR_COLOR_G=0;a.DEFAULT_STR_COLOR_B=0;a.DEFAULT_STATUS_COLOR_R=0;a.DEFAULT_STATUS_COLOR_G=0;a.DEFAULT_STATUS_COLOR_B=0;return a}();b.WWAConsts=d;d=function(){return function(){}}();b.LoaderResponse=d;d=function(){return function(){}}();
b.LoaderError=d;d=function(){return function(){}}();b.LoaderProgress=d;(function(a){a[a.MAP=1]="MAP";a[a.OBJECT=0]="OBJECT"})(b.PartsType||(b.PartsType={}));(function(a){a[a.INIT=0]="INIT";a[a.MAP_LOAD=1]="MAP_LOAD";a[a.OBJ_LOAD=2]="OBJ_LOAD";a[a.MAP_ATTR=3]="MAP_ATTR";a[a.OBJ_ATTR=4]="OBJ_ATTR";a[a.RAND_PARTS=5]="RAND_PARTS";a[a.MESSAGE=6]="MESSAGE"})(b.LoadStage||(b.LoadStage={}));d=function(){function a(a,e){void 0===a&&(a=0);void 0===e&&(e=0);this.x=a;this.y=e}a.prototype.equals=function(a){return this.x===
a.x&&this.y===a.y};a.prototype.substract=function(h){return new a(this.x-h.x,this.y-h.y)};a.prototype.clone=function(){return new a(this.x,this.y)};return a}();b.Coord=d;d=function(){return function(){this.systemMessage=this.mapCGName=this.charCGName=this.worldPassNumber=this.worldName=this.message=this.worldPassword=this.objectAttribute=this.mapAttribute=this.mapObject=this.map=this.messageNum=this.mapWidth=this.itemBox=this.statusGold=this.statusDefence=this.statusStrength=this.statusEnergy=this.statusEnergyMax=
this.isOldMap=this.objPartsMax=this.mapPartsMax=this.playerY=this.playerX=this.gameoverY=this.gameoverX=this.version=void 0;this.moves=0;this.statusColorB=this.statusColorG=this.statusColorR=this.fontColorB=this.fontColorG=this.fontColorR=this.frameOutColorB=this.frameOutColorG=this.frameOutColorR=this.frameColorB=this.frameColorG=this.frameColorR=this.imgClickY=this.imgClickX=this.bgm=this.delPlayerFlag=this.objectNoCollapseDefaultFlag=this.compatibleForOldMapFlag=this.disableSaveFlag=this.clickableItemSignImgPosY=
this.clickableItemSignImgPosX=this.playerImgPosY=this.playerImgPosX=this.yesnoImgPosY=this.yesnoImgPosX=void 0}}();b.WWAData=d})(loader_wwa_data||(loader_wwa_data={}));var loader_core;
(function(b){var d=function(){return function(a,e){this.mapData=a;this.extractEndPos=e}}(),a=function(){function a(e){this._fileName=e}a.prototype.requestMapData=function(){var a=this,c=new XMLHttpRequest;try{c.open("GET",this._fileName,!0),c.responseType="arraybuffer",c.onreadystatechange=function(){try{if(c.readyState===XMLHttpRequest.DONE)if(200===c.status||304===c.status)a.loadMapData(c.response),a.sendDataToMainProgram();else{if(404===c.status)throw Error("\u30de\u30c3\u30d7\u30c7\u30fc\u30bf\u300c"+
a._fileName+"\u300d\u304c\u898b\u3064\u304b\u308a\u307e\u305b\u3093\u3067\u3057\u305f\u3002\nHTTP\u30b9\u30c6\u30fc\u30bf\u30b9\u30b3\u30fc\u30c9\u306f "+c.status+"\u3067\u3059\u3002");if(403===c.status)throw Error("\u30de\u30c3\u30d7\u30c7\u30fc\u30bf\u300c"+a._fileName+"\u300d\u3092\u8aad\u307f\u53d6\u308b\u6a29\u9650\u304c\u306a\u3044\u3088\u3046\u3067\u3059\u3002\n\u7ba1\u7406\u8005\u306e\u65b9\u3078: \u30de\u30c3\u30d7\u30c7\u30fc\u30bf\u306e\u30d1\u30fc\u30df\u30c3\u30b7\u30e7\u30f3\u3092\u78ba\u8a8d\u3057\u3066\u304f\u3060\u3055\u3044\u3002\nHTTP\u30b9\u30c6\u30fc\u30bf\u30b9\u30b3\u30fc\u30c9\u306f "+
c.status+"\u3067\u3059\u3002");throw Error("\u30de\u30c3\u30d7\u30c7\u30fc\u30bf\u300c"+a._fileName+"\u300d\u306e\u8aad\u307f\u8fbc\u307f\u306b\u5931\u6557\u3057\u307e\u3057\u305f\u3002\nHTTP\u30b9\u30c6\u30fc\u30bf\u30b9\u30b3\u30fc\u30c9\u306f "+c.status+"\u3067\u3059\u3002");}}catch(b){a.sendErrorToMainProgram(b)}},c.send(null)}catch(b){this.sendErrorToMainProgram(Error("\u30ed\u30fc\u30c9\u30a8\u30e9\u30fc: \u30ed\u30fc\u30ab\u30eb\u30c6\u30b9\u30c8\u306e\u5834\u5408\u306f\u3001\u30d6\u30e9\u30a6\u30b6\u304c\u5bfe\u5fdc\u3057\u3066\u3044\u306a\u3044\u53ef\u80fd\u6027\u304c\u3042\u308a\u307e\u3059\u3002\n"+
b.message))}};a.prototype.loadMapData=function(a){try{this._srcData=new Uint8Array(a);var c=this.decodeMapData();this._dataExtractor=new WWADataExtractor(c.mapData);this._dataExtractor.extractAllData();this._dataJSObj=this._dataExtractor.getJSObject();this._currentPos=c.extractEndPos}catch(b){throw b;}this._loadAllTextData()};a.prototype._loadAllTextData=function(){var e;30<=this._srcData[WWADataExtractor.POS_VERSION]&&(this._dataJSObj.worldPassword=this._getMessageFromData());29>=this._srcData[WWADataExtractor.POS_VERSION]&&
(this._dataJSObj.messageNum=a.OLDVER_MESSAGE_MAX);this._dataJSObj.message=Array(this._dataJSObj.messageNum);for(e=0;e<this._dataJSObj.message.length;e++)this._dataJSObj.message[e]=this._getMessageFromData(),0===e%200&&b.sendProgressToMainProgram(e,this._dataJSObj.message.length,loader_wwa_data.LoadStage.MESSAGE);for(;10>this._dataJSObj.messageNum;)this._dataJSObj.message.push(""),this._dataJSObj.messageNum++;b.sendProgressToMainProgram(this._dataJSObj.message.length,this._dataJSObj.message.length,
loader_wwa_data.LoadStage.MESSAGE);this._dataJSObj.worldName=this._getMessageFromData();29>=this._srcData[WWADataExtractor.POS_VERSION]?this._dataJSObj.worldPassword=this._getMessageFromData():this._getMessageFromData();this._dataJSObj.worldPassNumber=""===this._dataJSObj.worldPassword?0:29<=this._srcData[WWADataExtractor.POS_VERSION]?(parseInt(this._dataJSObj.worldPassword)/10-1197)/17-2357:parseInt(this._dataJSObj.worldPassword);this._dataJSObj.charCGName=this._getMessageFromData();this._dataJSObj.mapCGName=
this._getMessageFromData();this._dataJSObj.systemMessage=Array(WWAConsts.SYSTEM_MESSAGE_NUM);for(e=0;e<WWAConsts.SYSTEM_MESSAGE_NUM;e++)this._dataJSObj.systemMessage[e]=30<=this._srcData[WWADataExtractor.POS_VERSION]?this._getMessageFromData():"";this._dataJSObj.yesnoImgPosX=loader_wwa_data.WWAConsts.IMGPOS_DEFAULT_YESNO_X;this._dataJSObj.yesnoImgPosY=loader_wwa_data.WWAConsts.IMGPOS_DEFAULT_YESNO_Y;this._dataJSObj.playerImgPosX=loader_wwa_data.WWAConsts.IMGPOS_DEFAULT_PLAYER_X;this._dataJSObj.playerImgPosY=
loader_wwa_data.WWAConsts.IMGPOS_DEFAULT_PLAYER_Y;this._dataJSObj.clickableItemSignImgPosX=loader_wwa_data.WWAConsts.IMGPOS_DEFAULT_CLICKABLE_ITEM_SIGN_X;this._dataJSObj.clickableItemSignImgPosY=loader_wwa_data.WWAConsts.IMGPOS_DEFAULT_CLICKABLE_ITEM_SIGN_Y;this._dataJSObj.disableSaveFlag=loader_wwa_data.WWAConsts.DEFAULT_DISABLE_SAVE;this._dataJSObj.isOldMap=loader_wwa_data.WWAConsts.DEFAULT_OLDMAP;this._dataJSObj.objectNoCollapseDefaultFlag=loader_wwa_data.WWAConsts.DEFAULT_OBJECT_NO_COLLAPSE;this._dataJSObj.delPlayerFlag=
!1;this._dataJSObj.bgm=0;this._dataJSObj.effectCoords=[];this._dataJSObj.effectWaits=0;this._dataJSObj.imgClickX=0;this._dataJSObj.imgClickY=0;this._dataJSObj.frameColorR=WWAConsts.DEFAULT_FRAME_COLOR_R;this._dataJSObj.frameColorG=WWAConsts.DEFAULT_FRAME_COLOR_G;this._dataJSObj.frameColorB=WWAConsts.DEFAULT_FRAME_COLOR_B;this._dataJSObj.frameOutColorR=WWAConsts.DEFAULT_FRAMEOUT_COLOR_R;this._dataJSObj.frameOutColorG=WWAConsts.DEFAULT_FRAMEOUT_COLOR_G;this._dataJSObj.frameOutColorB=WWAConsts.DEFAULT_FRAMEOUT_COLOR_B;
this._dataJSObj.fontColorR=WWAConsts.DEFAULT_STR_COLOR_R;this._dataJSObj.fontColorG=WWAConsts.DEFAULT_STR_COLOR_G;this._dataJSObj.fontColorB=WWAConsts.DEFAULT_STR_COLOR_B;this._dataJSObj.statusColorR=WWAConsts.DEFAULT_STATUS_COLOR_R;this._dataJSObj.statusColorG=WWAConsts.DEFAULT_STATUS_COLOR_G;this._dataJSObj.statusColorB=WWAConsts.DEFAULT_STATUS_COLOR_B};a.prototype.sendDataToMainProgram=function(){var a=new loader_wwa_data.LoaderResponse;a.progress=null;a.error=null;a.wwaData=this._dataJSObj;sendToMain(a)};
a.prototype.sendErrorToMainProgram=function(a){var c=new loader_wwa_data.LoaderResponse;c.wwaData=null;c.progress=null;c.error=new loader_wwa_data.LoaderError;c.error.name=a.name;c.error.message=a.message;sendToMain(c)};a.prototype.decodeMapData=function(){var e=new Uint8Array(this._srcData.length),c,b,g,k;for(b=c=0;c<this._srcData.length&&(0!==this._srcData[c]||0!==this._srcData[c+1]||0!==this._srcData[c+2]);c++){e[b++]=this._srcData[c];if(this._srcData[c]===this._srcData[c+1]){g=this._srcData[c+
2];for(k=0;k<g;k++)e[b++]=this._srcData[c];c+=2}b+255>=e.length&&(g=new Uint8Array(e.length+a.MEM_BLOCK),g.set(e),e=g)}try{console.log("EXTRACT DATA = "+b+" "+c)}catch(m){}try{this.checkCompletelyDecoded(e,b)}catch(l){throw l;}return new d(e,c+a.EXT_LAST_PADDING)};a.prototype._getMessageFromData=function(){for(var a="",c=0;1500>c&&(0!=this._srcData[this._currentPos+2*c]||0!=this._srcData[this._currentPos+2*c+1]);c++)a+=String.fromCharCode((this._srcData[this._currentPos+2*c+1]<<8)+this._srcData[this._currentPos+
2*c]);this._currentPos+=2*c+2;return a};a.prototype.checkCompletelyDecoded=function(a,c){var b,h=a[WWADataExtractor.POS_CHECK]+256*a[WWADataExtractor.POS_CHECK+1],d=0;if(29<=a[WWADataExtractor.POS_VERSION]){for(b=2;b<c;b++)d+=util.signedByte(a[b])*(b%8+1);d=d%65536&65535;if(h!==d)throw Error("\u30de\u30c3\u30d7\u30c7\u30fc\u30bf\u304c\u58ca\u308c\u3066\u3044\u308b\u3088\u3046\u3067\u3059\u3002\n \u30c1\u30a7\u30c3\u30af\u30b5\u30e0\u306e\u5024\u306f"+h+"\u3067\u3059\u304c\u3001\u5b9f\u969b\u306e\u548c\u306f"+
d+"\u3067\u3057\u305f\u3002");}};a.MEM_BLOCK=65E3;a.EXT_LAST_PADDING=3;a.OLDVER_MESSAGE_MAX=400;return a}();b.WWALoader=a;b.sendProgressToMainProgram=function(a,b,c){var f=new loader_wwa_data.LoaderResponse;f.error=null;f.wwaData=null;f.progress=new loader_wwa_data.LoaderProgress;f.progress.current=a;f.progress.total=b;f.progress.stage=c;sendToMain(f)}})(loader_core||(loader_core={}));var loader_extractor;
(function(b){var d=function(){function a(a){this._bitData=a;this._wwaData=new WWAData}a.prototype.extractAllData=function(){var b,e;this._wwaData.version=this._bitData[a.POS_VERSION];this._extractInitialParameters();this._currentPosition=29<this._wwaData.version?a.POS_MAPDATA_TOP:a.POS_OLD_MAPDATA_TOP;this._wwaData.map=this._getFieldDataFromBits(loader_wwa_data.PartsType.MAP,this._wwaData.mapPartsMax).concat();this._wwaData.mapObject=this._getFieldDataFromBits(loader_wwa_data.PartsType.OBJECT,this._wwaData.objPartsMax).concat();
b=29<this._wwaData.version?WWAConsts.MAP_ATR_MAX:WWAConsts.OLD_MAP_ATR_MAX;e=29<this._wwaData.version?WWAConsts.OBJ_ATR_MAX:WWAConsts.OLD_OBJ_ATR_MAX;this._wwaData.mapAttribute=this._getPartsDataFromBits(loader_wwa_data.PartsType.MAP,this._wwaData.mapPartsMax,b).concat();this._wwaData.objectAttribute=this._getPartsDataFromBits(loader_wwa_data.PartsType.OBJECT,this._wwaData.objPartsMax,e).concat();if(29>=this._wwaData.version)throw Error("\u3053\u306e\u30d0\u30fc\u30b8\u30e7\u30f3\u306eWWA\u306b\u306f\u3001\u73fe\u5728\u5bfe\u5fdc\u3057\u3066\u304a\u308a\u307e\u305b\u3093\u3002\n\u30de\u30c3\u30d7\u30c7\u30fc\u30bf\u30d0\u30fc\u30b8\u30e7\u30f3: "+
Math.floor(this._wwaData.version/10)+"."+this._wwaData.version%10);this._replaceAllRandomObjects()};a.prototype.getJSObject=function(){return this._wwaData};a.prototype._get1ByteNumber=function(a){return this._bitData[a]};a.prototype._get2BytesNumber=function(a){return this._bitData[a]+256*this._bitData[a+1]};a.prototype._extractInitialParameters=function(){29<this._wwaData.version?(this._wwaData.gameoverX=this._get2BytesNumber(a.POS_GAMEOVER_X),this._wwaData.gameoverY=this._get2BytesNumber(a.POS_GAMEOVER_Y),
this._wwaData.playerX=this._get2BytesNumber(a.POS_PLAYER_X),this._wwaData.playerY=this._get2BytesNumber(a.POS_PLAYER_Y),this._wwaData.mapPartsMax=this._get2BytesNumber(a.POS_MAP_COUNT),this._wwaData.objPartsMax=this._get2BytesNumber(a.POS_OBJ_COUNT),this._wwaData.isOldMap=!1):(this._wwaData.gameoverX=this._get1ByteNumber(a.POS_OLD_GAMEOVER_X),this._wwaData.gameoverY=this._get1ByteNumber(a.POS_OLD_GAMEOVER_Y),this._wwaData.playerX=this._get1ByteNumber(a.POS_OLD_PLAYER_X),this._wwaData.playerY=this._get1ByteNumber(a.POS_OLD_PLAYER_Y),
this._wwaData.mapPartsMax=this._get1ByteNumber(a.POS_OLD_MAP_COUNT),this._wwaData.objPartsMax=this._get1ByteNumber(a.POS_OLD_OBJ_COUNT),this._wwaData.isOldMap=!0);this._wwaData.statusEnergyMax=this._get2BytesNumber(a.POS_STATUS_ENERGY_MAX);this._wwaData.statusEnergy=this._get2BytesNumber(a.POS_STATUS_ENERGY);this._wwaData.statusStrength=this._get2BytesNumber(a.POS_STATUS_STRENGTH);this._wwaData.statusDefence=this._get2BytesNumber(a.POS_STATUS_DEFENCE);this._wwaData.statusGold=this._get2BytesNumber(a.POS_STATUS_GOLD);
this._extractInitialItemData();this._wwaData.mapWidth=this._get2BytesNumber(a.POS_MAP_SIZE);this._wwaData.messageNum=this._get2BytesNumber(a.POS_MESSAGE_NUM);28>this._wwaData.version?this._wwaData.mapWidth=71:29>=this._wwaData.version&&(this._wwaData.mapWidth=101)};a.prototype._extractInitialItemData=function(){var b,e=29<this._wwaData.version?a.POS_ITEMBOX_TOP:a.POS_OLD_ITEMBOX_TOP;this._wwaData.itemBox=Array(WWAConsts.ITEMBOX_SIZE);for(b=0;b<WWAConsts.ITEMBOX_SIZE;b++)this._wwaData.itemBox[b]=this._get1ByteNumber(e+
b)};a.prototype._getFieldDataFromBits=function(a,b){var c,f,d;d=util.new2DArray(this._wwaData.mapWidth,this._wwaData.mapWidth);for(c=0;c<this._wwaData.mapWidth;c++)for(f=0;f<this._wwaData.mapWidth;f++)29<this._wwaData.version?(d[c][f]=this._get2BytesNumber(this._currentPosition),this._currentPosition+=2):(d[c][f]=this._get1ByteNumber(this._currentPosition),this._currentPosition+=1),0===(c*this._wwaData.mapWidth+f)%200&&loader_core.sendProgressToMainProgram(c*this._wwaData.mapWidth+f,this._wwaData.mapWidth*
this._wwaData.mapWidth,a===loader_wwa_data.PartsType.MAP?loader_wwa_data.LoadStage.MAP_LOAD:loader_wwa_data.LoadStage.OBJ_LOAD),d[c][f]>=b&&(d[c][f]=0);loader_core.sendProgressToMainProgram(this._wwaData.mapWidth*this._wwaData.mapWidth,this._wwaData.mapWidth*this._wwaData.mapWidth,a===loader_wwa_data.PartsType.MAP?loader_wwa_data.LoadStage.MAP_LOAD:loader_wwa_data.LoadStage.OBJ_LOAD);return d};a.prototype._getPartsDataFromBits=function(a,b,c){var d,g,k;k=util.new2DArray(b,c);for(d=0;d<b;d++)for(g=
0;g<c;g++)0===(d*this._wwaData.mapWidth+g)%200&&loader_core.sendProgressToMainProgram(d*c+g,b*c,a===loader_wwa_data.PartsType.MAP?loader_wwa_data.LoadStage.MAP_ATTR:loader_wwa_data.LoadStage.OBJ_ATTR),k[d][g]=g===WWAConsts.ATR_CROP1||g===WWAConsts.ATR_CROP2?0:this._get2BytesNumber(this._currentPosition),this._currentPosition+=2;loader_core.sendProgressToMainProgram(b*c,b*c,a===loader_wwa_data.PartsType.MAP?loader_wwa_data.LoadStage.MAP_ATTR:loader_wwa_data.LoadStage.OBJ_ATTR);return k};a.prototype._replaceAllRandomObjects=
function(){loader_core.sendProgressToMainProgram(this._wwaData.mapWidth*this._wwaData.mapWidth,this._wwaData.mapWidth*this._wwaData.mapWidth,loader_wwa_data.LoadStage.RAND_PARTS)};a.prototype._replaceRandomObject=function(a,b,c){var d=Math.floor(10*Math.random());a=this._wwaData.objectAttribute[a][10+d];a>=this._wwaData.objPartsMax&&(a=0);this._wwaData.mapObject[b][c]=a};a.POS_CHECK=0;a.POS_VERSION=2;a.POS_OLD_MAP_COUNT=3;a.POS_OLD_OBJ_COUNT=4;a.POS_OLD_PLAYER_X=5;a.POS_OLD_PLAYER_Y=6;a.POS_STATUS_ENERGY=
10;a.POS_STATUS_STRENGTH=12;a.POS_STATUS_DEFENCE=14;a.POS_STATUS_GOLD=16;a.POS_OLD_GAMEOVER_X=18;a.POS_OLD_GAMEOVER_Y=19;a.POS_OLD_ITEMBOX_TOP=20;a.POS_STATUS_ENERGY_MAX=32;a.POS_MAP_COUNT=34;a.POS_OBJ_COUNT=36;a.POS_PLAYER_X=38;a.POS_PLAYER_Y=40;a.POS_GAMEOVER_X=42;a.POS_GAMEOVER_Y=44;a.POS_MAP_SIZE=46;a.POS_MESSAGE_NUM=48;a.POS_ITEMBOX_TOP=60;a.POS_MAPDATA_TOP=90;a.POS_OLD_MAPDATA_TOP=100;return a}();b.WWADataExtractor=d})(loader_extractor||(loader_extractor={}));
function sendToMain(b){loader_conf.conf.is_worker?postMessage(b):postMessage_noWorker({data:b})}var util=loader_util,WWAConsts=loader_wwa_data.WWAConsts,WWAData=loader_wwa_data.WWAData,WWADataExtractor=loader_extractor.WWADataExtractor,WWALoader=loader_core.WWALoader;
function loader_start(b){void 0!==b.data.fileName?(new WWALoader(b.data.fileName)).requestMapData():(b=new loader_wwa_data.LoaderResponse,b.wwaData=null,b.progress=null,b.error=new loader_wwa_data.LoaderError,b.error.name="",b.error.message="\u30de\u30c3\u30d7\u30c7\u30fc\u30bf\u306e\u30d5\u30a1\u30a4\u30eb\u540d\u304c\u6307\u5b9a\u3055\u308c\u3066\u3044\u307e\u305b\u3093\u3002",sendToMain(b))}loader_conf.conf.is_worker&&addEventListener("message",loader_start);
