page:

  # タイトルです
  # 無指定はデフォルトのタイトルが指定されます
  title: "World Wide Adventure Wing"

  # 生成するHTMLがWWA開発用のモードかどうかを指定します
  # 無指定は false と同じ扱いになります
  isDevMode: false

  # WWA に関する設定です
  # 各項目無指定はデフォルトになります
  wwa:
    urlgateEnable: true
    
    resources:
      # マップデータの場所を指定します
      mapdata: "mapdata.dat"

      audio:
        # オーディオファイルを配置するディレクトリを指定します　
        dir: "./audio/"
        # オーディオファイル内のaudioJsのファイル位置を指定します
        js: "audio.min.js"

      # wwa.js のファイル名を変更している場合は指定します
      wwaJs: "wwa.js"

      # wwa.css のファイル名を変更している場合は指定します
      wwaCss: "wwa.css"

      # タイトル画像を指定します
      titleImg: "cover.gif"

      # 開発モードの場合はcrypro.js の場所を指定します
      cryptoJsInDevMode: "cryptojs/aes.js"

  copyrights:
    # WWA本家の著作権情報をページに記述する場合はもろもろ指定します
    -
      startYear: 1996
      presentYear: 2016
      credit: NAO
      product: 
        name: "World Wide Adventure"
        href: "http://wwajp.com/"
      genre: "Internet RPG"

    # WWAWingの著作権情報をページに記述する場合はもろもろ指定します
    -
      startYear: 2013
      presentYear: 2018
      credit: "WWA Wing Team"
      product: 
        name: "WWA Wing"
        href: "https://wwawing.com/"

    # その他著作権表記を追加したい場合はコピペしてください
