name: "WWA Wing Publish"

permissions:
  id-token: write  # Required for OIDC
  contents: write

on:
  workflow_dispatch:
    inputs:
      version:
        description: "バージョンを入力 (major, minor, patch) 安定版は原則 patch のみ"
        required: true
        default: "patch"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: ./.github/actions/init
        with:
          lfs: true
      ## 安定版ではタグは latest に固定します
      - name: "Publish"
        run: |
          npm run version-up -- ${{ github.event.inputs.version }} --yes
          export NEW_VERSION=$(node -e 'process.stdout.write(require("./lerna.json").version)')
          npm ci
          git add -u package-lock.json lerna.json packages/*/package.json
          git commit -m "v$NEW_VERSION"
          git tag "v$NEW_VERSION"
          git push origin HEAD --tags
          npm run publish:all -- --dist-tag latest --no-verify-access --yes
