name: "WWA Wing Publish"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "バージョンを入力 (patch/minor/major/X.X.X-hogehoge.X)"
        required: true
        default: "patch"
      tag:
        description: "publish に使うタグを入力 (普通にリリースしたい場合:latest)"
        required: true
        default: "latest"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      
      - name: "Configure"
        run: |
          git config user.name "[Automatically Released] Matsuyuki"
          git config user.email "matsuyuki.eca@gmail.com"

      - name: "Install"
        run: |
          npm i -g npm@8
          npm install
      
      - name: "Publish"
        # lerna version でバージョンを上げた後、npm i をすると package-lock.json に差分が出てしまうので...
        run: |
          npm run version-up -- ${{ github.event.inputs.version }} --yes
          export NEW_VERSION=$(node -e 'process.stdout.write(require("./lerna.json").version)')
          git push origin HEAD --tags
          npm run publish:all -- --dist-tag ${{ github.event.inputs.tag }} --no-verify-access --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: "check"
        run: git diff
        if: ${{ failure() }}