name: "WWA Wing Publish"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "バージョンを入力 (patch/minor/major/X.Y.Z-hogehoge.based-on.A.B.C.p.N)"
        required: true
        default: "patch"
      tag:
        description: "publish に使うタグを入力 (普通にリリースしたい場合:latest)"
        required: true
        default: "latest"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      
      - name: "Configure"
        run: |
          git config user.name "[Automatically Released] Matsuyuki"
          git config user.email "matsuyuki.eca@gmail.com"

      - name: restore node_modules
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      
      - name: restore node.exe
        uses: actions/cache@v4
        with:
          path: './packages/assets/exe/node.exe'
          key: node-exe-${{ hashFiles('./packages/assets/exe/node.exe') }}

      - name: "Install"
        run: |
          git lfs pull
          npm i -g npm@10
          npm install
      
      - name: "Publish"
        # lerna version でバージョンを上げた後、npm i をすると package-lock.json に差分が出てしまうので...
        run: |
          npm run version-up -- ${{ github.event.inputs.version }} --yes
          export NEW_VERSION=$(node -e 'process.stdout.write(require("./lerna.json").version)')
          npm install
          git add -u package-lock.json lerna.json packages/*/package.json
          git commit -m "v$NEW_VERSION"
          git tag "v$NEW_VERSION"
          git push origin HEAD --tags
          npm run publish:all -- --dist-tag ${{ github.event.inputs.tag }} --no-verify-access --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
