name: "WWA Wing Release"

on:
  release:
    types:
      - created

  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: "Set Env"
        run: "echo \"WWA_WING_VERSION=$(node -e \"console.log(require('./packages/engine/package.json').version)\")\" >> $GITHUB_ENV"

      - name: restore node_modules
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      - name: "Install & Build"
        run: |
          npm i -g npm@8
          npm install
          npm run build
          npm run generate
          file ./packages/all/dist/wwawing-dist/wwa.js
          file ./packages/all/dist/wwawing-update/wwa.js

      - name: "Upload distributions"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: "cd packages/all && npm run release && cd ../.."

      # WWAWing/sites リポジトリ側にある、新バージョンの公開を行うワークフローを呼び出す
      - name: "Create pull request to WWAWing/sites respoitory"
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.WWA_WING_CALL_WORKFLOW_TOKEN }}
          repository: WWAWing/sites
          event-type: wwa-wing-release
          client-payload: '{"targetVersion": "${{ env.WWA_WING_VERSION }}"}'
