name: "WWA Wing Release"

on:
  release:
    types:
      - created

  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'

      - name: "Set Env"
        run: "echo \"WWA_WING_VERSION=$(node -e \"console.log(require('./packages/engine/package.json').version)\")\" >> $GITHUB_ENV"

      - name: restore node_modules
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      - name: restore node.exe
        uses: actions/cache@v4
        with:
          path: './packages/assets/exe/node.exe'
          key: node-exe-${{ hashFiles('./packages/assets/exe/node.exe') }}

      - name: "Install & Build"
        run: |
          npm i -g npm@10
          git lfs pull
          npm install
          npm run build
          npm run generate

      - name: "Upload distributions"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: "cd packages/all && npm run release && cd ../.."

      # WWAWing/sites リポジトリ側にある、新バージョンの公開を行うワークフローを呼び出す
      - name: "Create pull request to WWAWing/sites respoitory"
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.WWA_WING_CALL_WORKFLOW_TOKEN }}
          repository: WWAWing/sites
          event-type: wwa-wing-release
          client-payload: '{"targetVersion": "${{ env.WWA_WING_VERSION }}"}'
