name: "WWA Wing Release"

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "Install SSH Key for WWAWing/sites"
        uses: "shimataro/ssh-key-action@v2"
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_ed25519
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: "Set Env"
        run: "echo \"WWA_WING_VERSION=$(node -e \"console.log(require('./packages/engine/package.json').version)\")\" >> $GITHUB_ENV"

      - name: "Print version"
        run: "echo $WWA_WING_VERSION"

      - name: "Install"
        run: "npm install"

      - name: "Create pull request to WWAWing/Sites respoitory"
        env:
          WWA_WING_RELEASE_TOKEN: ${{ secrets.WWA_WING_RELEASE_TOKEN }}
        run: "cd packages/all && ./scripts/update-sites.sh && cd ../.."
