name: "WWA Wing Test"

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: ./.github/actions/init
        with:
          lfs: true
      - name: "test"
        run: |
          npm test
